# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def554004f138320bb9674a54c55fd18b4b643c53703c485263abca25787f74fe8c12cdfbd4211ad993840b5394de76ce4721a12fd7743003ef4b1443534c8a9

test:
  secret_key_base: d0ab2d75795f4bddabfb53573d63f95548b27d424eb80c6dd06bdd914a04a5cbb088f706f4820853c43e4cca091da6ea1debd2da5f2e13d40db613124cdb3101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
